apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: r506ar653-go 
  janus-idp.io/tekton: r506ar653-go
  backstage.io/kubernetes-id: r506ar653-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: r506ar653-go
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  